services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - PGTZ=UTC # Set timezone for PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
    name: postgres-data-volume

networks:
  app-network:
    driver: bridge
